### ISSUE TITLE
Awesome package, needs a little love 

### ISSUE THREAD

**Issue by rasmusfjord** [thecogworks/meganav#1]
Hey Guys 

Awesome package, we were just about to build something like this our self.

I just installed it into a new project a got a bit of feedback to take from awesome to MEGA SUPER AWESOME :) 

First of all the nuget package isnt working, it installs the package in Umbraco/Ui/app_plugins/, also the package dosnt contain the manifest file.

So i choose to pull down the zip and manually install it, and here its good :) 👍 

I have created a meganav with depth of 2, and it works great, though I cannot drag an element below a nested group. Oh i just found out how you have to put it where its nested and then pull it outwards.

Maybe give a bit of highlighting about how you nest an item, its intuitive when you know how to use it but first tries it dosnt make sense for me. Had a few collegues mess around with it.

So this is only to give some feedback, and the package is just AWESOME :)

**Comment by callumbwhyte** [comment]
Hey @rasmusfjord,

Glad you like the package!

I'm aware of the NuGet issue and we're working to resolve it ASAP. I'll update this thread once it's resolved. :-)

Thanks for the usability feedback - I'll take this into account for the future release. This is the first version and I'm hoping to release many more features and improvements soon.

Callum

**Comment by mzajkowski** [comment]
As NuGet is fixed now, I'm closing this issue. Still needs some love though! ;)
