### ISSUE TITLE
Link title is not retrieved for node after it's saved

### ISSUE THREAD

**Issue by mzajkowski** [thecogworks/meganav#10]
MeganavItem is saved correctly into db (with values applied during first configuration). But when we're retrieving data for the 2nd time it's changed = empty, cause we're building items using API method which is getting values from IPublishedContent, creating angular model based on them and just extending it with the other data.

**Comment by callumbwhyte** [comment]
Thanks for raising this @mzajkowski!

This issue was fixing in the v1.1.0 release which just launched! You can download right now from all the usual places including NuGet and Our Umbraco

Cheers! :-)
