### ISSUE TITLE
Nuget installation installs App_Plugin and Views folders in two locations

### ISSUE THREAD

**Issue by ProNotion** [thecogworks/meganav#17]
For some reason installing via nuget puts files in the following locations in my solution:

```
App_Plugins/Meganav
Views
```

and

```
Web/ui/App_Plugins/Meganav
Web/ui/Views
```

**Comment by callumbwhyte** [comment]
Big thanks for raising this @ProNotion! #h5yr

This is something we've been aware of and has been fixed as part of the latest release, v1.1.0. You can download right now from all the usual places including NuGet and Our Umbraco

Cheers!
