### ISSUE TITLE
The documentation PDF on Umbraco is reporting itself as corrupt.

### ISSUE THREAD

**Issue by cgarveyie** [thecogworks/meganav#2]
Can't open it with Acrobat Reader anyway.. says the PDF is corrupt.

Great idea though, will help out if I can.

**Comment by AnthonyCogworks** [comment]
It worked on my machine :)

But yes, you're right it didnt work in other apps such as Reader, and Chrome. New doc is up now. 

Hopefully it works for you:

https://our.umbraco.org/FileDownload?id=17174
