### ISSUE TITLE
Meganavitem does not contain a definition for 'Children'

### ISSUE THREAD

**Issue by blachawk** [thecogworks/meganav#21]
The integration process using model shows us how to get a single level navigation.  But how do we get 2nd level links?  Visual Studio is telling me that `Meganavitem` does not contain a definition for 'Children'.  This was my attempt...

```
@{
    if (Model.HasValue("MytopNav"))
    {
        <ul>
            @foreach (var item in Model.MytopNav)
            {
                <li class="dropdown">@item.Title

                    @if (item.Children().Any())
                    {
                        ...

                    }
            </li>
            }
        </ul>
    }
}
```

**Comment by blachawk** [comment]
I solved it.  Had to change Children() to Children

**Comment by callumbwhyte** [comment]
Glad you managed to solve this one yourself!
