### ISSUE TITLE
How to render partial  "ExampleNavigation" in Master template?

### ISSUE THREAD

**Issue by mjharaldsson** [thecogworks/meganav#23]
Hi,

Sorry for a stupid question, but how do I render the partial "ExampleNavigation" in the master template?

On my Master template I  try to render the partial like so:

```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{ 
    Layout = null;
}

@Html.Partial("ExampleNavigation", Model.Content.GetPropertyValue<IEnumerable<MeganavItem>>("topNavigation"))
```

But the MeganavItem shows the error "The type or namespace 'MeganavItem' could not be found". So I tried adding the namespace like so:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Cogworks.Meganav.Models

@{ 
    Layout = null;
}

@Html.Partial("ExampleNavigation", Model.Content.GetPropertyValue<IEnumerable<MeganavItem>>("topNavigation"))
```

This gives me no error in Visual Studio, but instead this Server Error message:

> The model item passed into the dictionary is of type 'Umbraco.Web.Models.RenderModel', but this dictionary requires a model item of type 'System.Collections.Generic.IEnumerable`1[Cogworks.Meganav.Models.MeganavItem]'.

Can you help me solve this please? :)

**Comment by callumbwhyte** [comment]
Hello,

Thank you for using Meganav, I'm sorry you're having some issues getting up and running!

The steps you've gone through so far and your final code sample look good to me, it's very difficult to see where this problem might be coming from as the code looks correct.

My guess would be that `Model.Content.GetPropertyValue<IEnumerable<MeganavItem>>("topNavigation")` is returning a `null` which is then passed through to the partial. Does a property definitely exist on the node you are testing on with the alias "topNavigation"?

**Comment by mjharaldsson** [comment]
Hi again,

Thank you for your quick reply!

Yes, propertiy exists on the node I'm testing. I noticed that the navigation renders on the "Home Page" but when I navigate to one of the child pages I get the following error message: 

> The model item passed into the dictionary is of type 'Umbraco.Web.Models.RenderModel', but this dictionary requires a model item of type 'System.Collections.Generic.IEnumerable`1[Cogworks.Meganav.Models.MeganavItem]'.

This is how it renders on the Home Page:

- Home (Level: 0) (This is where I build the navigation structure with Meganav datatype)
- Products (Level: 0)
- News (Level: 0)
- Customer Service (Level: 0)
-- Contact Us (Level: 1)
-- About Us (Level: 1)
- Etc.

Very weird and I'm 100% sure I'm doing something really stupid, just have to figure out what :).

**Comment by mjharaldsson** [comment]
That did the trick! 👍 

Thank you so very much for your support and excellent package! It really makes it so much easier to build more complex and flexible menu structure for your website. 

The editors are gonna be so happy now! :)

**Comment by callumbwhyte** [comment]
Glad I could help, enjoy using Meganav!
