### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by penskyc** [thecogworks/meganav#3]
Forgive me, but I am fairly new to Umbraco and I am not quite sure how to call this partial

@{ Html.RenderPartial("ExampleNavigation", (MeganavItem)Model.Content.GetPropertyValue<IEnumerable<MeganavItem>>("mainMenu")); }

Thank you for any help in advanced

**Comment by callumbwhyte** [comment]
Hey @penskyc,

Thanks for downloading the package!

If you've named your property "mainMenu" you can load the "ExampleNavigation" like so:

    @Html.Partial("ExampleNavigation", Model.Content.GetPropertyValue<IEnumerable<MeganavItem>>("mainMenu"))

Let me know if you have any other questions :-)

Callum
