### ISSUE TITLE
Meganav javascript appears to be broken on Umbraco v7.12

### ISSUE THREAD

**Issue by MMasey** [thecogworks/meganav#32]
On a fresh Umbraco install i've installed MegaNav and when viewing it on the document type it appears broken. The UI looks like so

![image](https://user-images.githubusercontent.com/6573613/44353517-227a5d00-a49f-11e8-8291-73c8cb73aeec.png)

Looking at the console the JavaScript appears to be failing at the LinkPickerController, which may have changed in a recent umbraco update.

![image](https://user-images.githubusercontent.com/6573613/44353489-07a7e880-a49f-11e8-86f5-b67ff05b7c03.png)

**Comment by callumbwhyte** [comment]
Thanks for raising this @MMasey, and thanks for the clear steps to replicate!

I have been able to replicate this in v7.12 and I am currently looking into a fix.

**Comment by callumbwhyte** [comment]
This issue is now fixed in release 1.1.2 - available for download on Our Umbraco(https://our.umbraco.com/projects/website-utilities/meganav/) and [Nuget](https://www.nuget.org/packages/Cogworks.Meganav/1.1.2) now!

Please let me know if any other issues come up!
