### ISSUE TITLE
Unable to add initial menu item

### ISSUE THREAD

**Issue by Asadlerpwcom** [thecogworks/meganav#35]
Hi,

I have installed the NuGet package version 1.1.2, and when i click the Add button to add the first menu item i am redirected through to the umbraco admin area homepage.

The javascript console is throwing this error:

`Error: Argument 'Cogworks.Meganav.MeganavController' is not a function, got undefined`

**Comment by Asadlerpwcom** [comment]
After reinstalling the NuGet package it seems to be working now.

**Comment by callumbwhyte** [comment]
Glad you were able to find a solution! 👍
