### ISSUE TITLE
Node name is not updating, when picking another node

### ISSUE THREAD

**Issue by bjarnef** [thecogworks/meganav#4]
It seems the node name doesn't update, when picking another node, while the url does. However it does update the node name after save and refresh window.
Tested with Umbraco 7.5.9

![image](https://cloud.githubusercontent.com/assets/2919859/23837255/a2b723da-0785-11e7-8ce0-c36abbefe129.png)

I think it should these should first update on submit callback, because if I pick another node, then click cancel and save and publish, it save the other picked node (which I wanted to cancel) and it is inkonsistent with how the another pickers works in Umbraco.

It should not have saved this node, but the originally "Home" node.
![image](https://cloud.githubusercontent.com/assets/2919859/23837320/8c01b730-0786-11e7-8375-f0f3cf4a7723.png)

It seems it use the same model directly instead of the model from the callback.

**Comment by callumbwhyte** [comment]
Thanks for raising this @bjarnef!

I am happy to say this issue is now fixed in the latest release, v1.1.0! You can download it right now from all the usual places including NuGet and Our Umbraco

Thanks :-)
