### ISSUE TITLE
Error when picking media

### ISSUE THREAD

**Issue by bjarnef** [thecogworks/meganav#6]
The meganav picker allow to pick media item, however it shows and error when clicking "edit" afterwards.

![image](https://cloud.githubusercontent.com/assets/2919859/23889705/ae1301d6-088e-11e7-839d-3c041654bc96.png)

![image](https://cloud.githubusercontent.com/assets/2919859/23889716/b8955f46-088e-11e7-803a-07026af38440.png)

**Comment by callumbwhyte** [comment]
Thanks for raising this issue @bjarnef!

It seems this feature was included in Meganav v1.0.0 by mistake... Meganav is based on the Umbraco Link Picker and the option to pick media items is default behaviour.

In the latest v1.1.0 release we have slightly reworked the way Meganav works to accommodate a feature coming in vNext, and as part of doing that we removed the option to pick media. We understand there may still be a need to pick links to documents, etc, from the media library but don't feel picking those in the same way as you choose nav items is appropriate - this is something we'll be addressing in a future release. :-) If you do require links to media items in your navigation right now I would suggest just pasting the URL into a custom link item.

As for now this option has been removed I will close this issue. Thanks again! #h5yr
