### ISSUE TITLE
Lecacy icons are not resolved

### ISSUE THREAD

**Issue by bjarnef** [thecogworks/meganav#7]
When using lecacy icons, e.g. for "Blog" node in Fanoe starterkit, the icon is not resolved.

![image](https://cloud.githubusercontent.com/assets/2919859/23889801/21e7bdfe-088f-11e7-87b4-9a606742d9a4.png)

After refresh
![image](https://cloud.githubusercontent.com/assets/2919859/23889832/3fcf0930-088f-11e7-8108-48f2e3656578.png)

In UrlPicker we have used this to convert the lecacy icon, where Umbraco use the `iconHelper` aswell for tree icons.

https://github.com/kgiszewski/uWestFest/blob/6dca20e30ce574ee2c652f002c3d63e2b5ae73bf/urlpicker/app/scripts/controllers/url.picker.controller.js#L318-L324

**Comment by mzajkowski** [comment]
Definitely we will use what you've done to also support legacy icons. Thanks for sharing your code @bjarnef!

**Comment by callumbwhyte** [comment]
Thanks for raising this one as well @bjarnef! This fix is also in our latest v1.1.0 release which you can download right now from all the usual places including NuGet and Our Umbraco
