### ISSUE TITLE
Problem after upgrade to Umbraco v12.3.6. Website don't start.

### ISSUE THREAD

**Issue by afabri73** [thecogworks/meganav#73]
Today I upgrade Umbraco 11.5.0 to 12.3.6 and I encourred in the following error:

![Meganav - Error](https://github.com/callumbwhyte/meganav/assets/6714121/97977920-662f-425e-8b35-8e6945c3862b)

How can I  resolve the problem?
Can you help me?

Thank you
Adriano

**Comment by afabri73** [comment]
Hi callumbwhyte,
I tried to clone your project to understand the problem.
So...after some attemps, I think I found the solution.

I think you must update the NuGet package **_umbraco.cms.Infrastructure_** to v12.3.6 and update also the **_internal class PublishedElementProperty_** by adding the following line in the _**PublishedElementProperty.cs**_ file:

`public object GetDeliveryApiValue(bool expanding, string culture = null, string segment = null) => _objectValue.Value;`

Doing that, the problem seems to be fixed.
Can you try to update your package and re-publish on NuGet so we can continue to use also in Umbraco v12.3.6 installations?

Thank you in advance for the support
Adriano

**Comment by afabri73** [comment]
Hi callumbwhite,
you pushed a pull request (#74) to resolve this issue.
Try it and I hope this fix the problem.

Bye
Adriano

**Comment by callumbwhyte** [comment]
Hello everybody,

Thanks for your continued use & support for Meganav.

A fix including support for Umbraco v12 and v13 has been merged – you will find v4.1.0 of Meganav is now available on NuGet.

Callum

**Comment by afabri73** [comment]
Hi Callum,
sorry for delay and thank you for the support.
Today I updated meganav to version 4.1.0 but unfortunately I have problems also with this version (Umbraco v12.3.9)

When I try to launch Umbraco, I immediately receive this error:
![image](https://github.com/callumbwhyte/meganav/assets/6714121/cb306cfa-2767-473e-8a82-940845a945cb)

I need to do something else for meganav configuration before start Umbraco?

Adriano
