### ISSUE TITLE
Support for Umbraco 13

### ISSUE THREAD

**Issue by mcl-sz** [thecogworks/meganav#75]
Unfortunately MegaNav does not work with Umbraco 13 yet. I think it seems to have the same cause as this issue https://github.com/callumbwhyte/meganav/issues/72

If I add this pull request https://github.com/callumbwhyte/meganav/pull/74 then I can make a successful build but the Content Delivery Api throws an error when called

**Comment by mcl-sz** [comment]
The problem arises as soon as a content item is added to the MegaNav. If it only consists of external links there is no problem. Strangely enough, the GetDeliveryApiValue method is not called, which is what I expected.

**Comment by afabri73** [comment]
Hi mcl-sz,
yes...I encountered in the same problem with Umbraco 12 and I already opened a ticket (#73) and sent a pull request (#74) with the updated code hoping that the update would be done soon, but unfortunately it hasn't done yet.

We must waiting callumbwhite ore use another package

Adriano

**Comment by mcl-sz** [comment]
Hi @afabri73, 

Adding a pull request indeed solves the problem of being able to build packages, but unfortunately it does not solve the problem with using MegaNav in the Content Delivery API. I've looked into it but I can't see where it's going wrong. Would you also like to take a look at this?

**Comment by mcl-sz** [comment]
Hi @callumbwhyte  and @afabri73 , i've added an pull request https://github.com/callumbwhyte/meganav/pull/76 for adding support for Umbraco 12.6.3 and above. (This is my first pull-request on GitHub so maybe i made mistakes). The Delivery Api is now working and based the datastructure on the Umbraco MultiUrlPicker. I've also added persistance for the QueryString.

**Comment by callumbwhyte** [comment]
Hello everybody,

Thanks for your continued use & support for Meganav.

A fix including support for Umbraco v12 and v13 has been merged – you will find v4.1.0 of Meganav is now available on NuGet.

Callum

**Comment by mcl-sz** [comment]
Thanks for the release, but no support for the DeliveryApi unfortunately. Was there a reason not to include my PR in this release?

**Comment by afabri73** [comment]
Thank you Callum, tomorrow I'll try to install the new version.

Adriano

**Comment by afabri73** [comment]
Sorry for delay.
Unfortunately I have problems also with version 4.1.0 (umbraco v12.3.9)

Here you can find the screenshot of the error:
https://github.com/callumbwhyte/meganav/issues/73#issuecomment-2049368735
